# Generated by Django 4.2.4 on 2023-12-24 11:35

from django.db import migrations, models
import kritika_main.models


class Migration(migrations.Migration):
    dependencies = [
        ("kritika_main", "0008_alter_post_full_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kritikauser",
            name="role",
            field=models.CharField(
                default=kritika_main.models.Role["CLIENT"], max_length=12
            ),
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
